### ISSUE TITLE
[Linux] Missing String.hasPrefix()  

### ISSUE THREAD

**Issue by luxvio** [AE9RB/SwiftGL#2]
Hello !
I've been poking around with the lib and found this error when compiling the demo in this repo.

As far as I know (and tested), this is solved importing `Foundation` in `SwiftGL.swift` (or writing an alternative implementation with String.characters, which could allow not importing `Foundation`).

And ... that along with adjusting glfw modulemap "link" to match my distro naming of the lib, makes `SwiftGL` compiles and run smoothly :D

Ty for making this project !
Regards.

**Comment by AE9RB** [comment]
Can you try `support[support.startIndex] == "+"` (and "-") on your platform. Mine imports Foundation whether I want it or not.

**Comment by luxvio** [comment]
Builds, and runs purrfectly :smile:

**Comment by AE9RB** [comment]
Thanks. I'll make sure this gets in the next release. Reopening so I don't forget.

**Comment by AE9RB** [comment]
committed 5ff97d3a284c4cca62dcffc31d9a92e4b7b5ff37
